## Original 
# general {
#     lock_cmd = pidof hyprlock || hyprlock
#     before_sleep_cmd = hyprlock
#     ignore_dbus_inhibit = false  # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
#     ignore_systemd_inhibit = false  # whether to ignore systemd-inhibit --what=idle inhibitors
# }

# After a period of inactivity, the screen dims,
# and brightness returns with any action.
# listener {
#     timeout = 5 # in seconds
#     on-timeout = brightnessctl -s && brightnessctl s 1% # Save and set brightness to 1%
#     on-resume = brightnessctl -r # Restore brightness on activity
# }

# # Turns off display (but not if media is playing)
# listener {
#     timeout = 10 # in seconds
#     on-timeout = hyprctl dispatch dpms off # Turn off display
#     on-resume = hyprctl dispatch dpms on   # Turn display back on
# }

# # # After a period of inactivity, the screen locks
# listener {
#     timeout = 30 # in seconds
#     on-timeout = hyprlock
# }

# After a period of inactivity, the device enters sleep mode
# listener {
#     timeout = 600 # in seconds           
#     on-timeout = systemctl suspend
# }




## My Own HyprIdle Configuration File 

general {
    lock_cmd = caelestia shell lock lock
    before_sleep_cmd = caelestia shell lock lock
    ignore_dbus_inhibit = false  # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false  # whether to ignore systemd-inhibit --what=idle inhibitors
    after_sleep_cmd = hyprctl dispatch dpms on && sleep 1 && hyprctl dispatch focusmonitor DP-1 
}


listener {
    timeout = 300
    on-timeout = caelestia shell brightness set 0.05
    on-resume  = caelestia shell brightness setFor DP-1 0.6
}

listener {
    timeout = 600
    on-timeout = sh -c '~/.local/bin/media-active.sh || caelestia shell lock lock'
}

listener {
    timeout = 601
    on-timeout = sh -c '~/.local/bin/media-active.sh || hyprctl dispatch dpms off'
    on-resume  = hyprctl dispatch dpms on
}

listener {
    timeout = 900
    on-timeout = sh -c '~/.local/bin/media-active.sh && exit 0
                            caelestia shell lock lock
                            systemctl suspend'

}
