
# ▒█▀▄▀█ █▀▀█ █▀▀▄ ░▀░ ▀▀█▀▀ █▀▀█ █▀▀█ █▀▀ 
# ▒█▒█▒█ █░░█ █░░█ ▀█▀ ░░█░░ █░░█ █▄▄▀ ▀▀█ 
# ▒█░░▒█ ▀▀▀▀ ▀░░▀ ▀▀▀ ░░▀░░ ▀▀▀▀ ▀░▀▀ ▀▀▀
# See https://wiki.hyprland.org/Configuring/Monitors/

# Monitor principal (MSI)
monitor=DP-1,2560x1080@200,0x0,1

# Monitor Secundario (Spectre DP adapter)
monitor=DP-2,1920x1080@74.97,630x-1080,1

# Monitor Secundario (Spectre HDMI)
monitor=HDMI-A-1,1920x1080@74.97,630x-1080,1

# Monitor Tercer (Sceptre a la derecha)
# monitor=HDMI-A-1,1920x1080@74.97,2560x-1080,1



workspace=1,monitor:DP-1